/**
 * VERCEL SERVERLESS FUNCTION - ILLUMINE AGENT
 * Endpoint: /api/agent
 * Triggered by cron job daily at 08:00 UTC
 * Generates content, logs to Google Sheets, posts to Buffer
 */

import Anthropic from "@anthropic-ai/sdk";
import { sheets_v4 } from "@googleapis/sheets";
import { google } from "googleapis";

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

// Initialize Google Sheets
const auth = new google.auth.GoogleAuth({
  credentials: JSON.parse(process.env.GOOGLE_SERVICE_ACCOUNT_JSON),
  scopes: ["https://www.googleapis.com/auth/spreadsheets"],
});

const sheetsClient = google.sheets({ version: "v4", auth });

/**
 * Main agent logic - generates content and logs to sheet
 */
async function runAgent() {
  console.log("[AGENT] Starting Illumine social media agent...");

  try {
    // Step 1: Generate content using Claude
    console.log("[AGENT] Generating content with Claude...");
    const contentPrompt = `Generate 2 distinct social media posts for D2C founders about paid marketing psychology.

Post 1 (LinkedIn - professional, ~280 chars):
- Focus on psychology/behavioral economics insight
- Include research reference
- Professional tone

Post 2 (Instagram - engaging, ~150 chars):
- Same psychology insight but more conversational
- Include relevant hashtags
- Engaging/conversational tone

Format response as JSON with keys: linkedin_text, instagram_text`;

    const response = await anthropic.messages.create({
      model: "claude-opus-4-20250805",
      max_tokens: 1024,
      messages: [
        {
          role: "user",
          content: contentPrompt,
        },
      ],
    });

    const generatedText =
      response.content[0].type === "text" ? response.content[0].text : "";

    // Parse response
    let content = { linkedin_text: "", instagram_text: "" };
    try {
      const jsonMatch = generatedText.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        content = JSON.parse(jsonMatch[0]);
      }
    } catch (e) {
      console.log("[AGENT] Using raw text response");
      content = {
        linkedin_text: generatedText.substring(0, 280),
        instagram_text: generatedText.substring(0, 150),
      };
    }

    console.log("[AGENT] Content generated:");
    console.log("  LinkedIn:", content.linkedin_text);
    console.log("  Instagram:", content.instagram_text);

    // Step 2: Log to Google Sheets
    console.log("[AGENT] Logging to Google Sheets...");
    const sheetResponse = await sheetsClient.spreadsheets.values.append({
      spreadsheetId: process.env.GOOGLE_SHEET_ID,
      range: "CONTENT_PENDING_REVIEW!A:H",
      valueInputOption: "USER_ENTERED",
      requestBody: {
        values: [
          [
            new Date().toISOString().split("T")[0],
            "PENDING",
            "both",
            content.linkedin_text + " | " + content.instagram_text,
            content.linkedin_text,
            content.instagram_text,
            "Auto-generated by Illumine Agent",
            "",
          ],
        ],
      },
    });

    console.log("[AGENT] Logged to Google Sheet:", sheetResponse.data);

    // Step 3: Log activity
    await sheetsClient.spreadsheets.values.append({
      spreadsheetId: process.env.GOOGLE_SHEET_ID,
      range: "ACTIVITY_LOG!A:E",
      valueInputOption: "USER_ENTERED",
      requestBody: {
        values: [
          [
            new Date().toISOString(),
            "CONTENT_GENERATED",
            "PENDING_REVIEW",
            `Generated LinkedIn + Instagram content`,
            "success",
          ],
        ],
      },
    });

    console.log("[AGENT] Activity logged");

    return {
      status: 200,
      message: "Agent executed successfully",
      content: content,
    };
  } catch (error) {
    console.error("[AGENT ERROR]", error);

    // Log error to sheet
    try {
      await sheetsClient.spreadsheets.values.append({
        spreadsheetId: process.env.GOOGLE_SHEET_ID,
        range: "ACTIVITY_LOG!A:E",
        valueInputOption: "USER_ENTERED",
        requestBody: {
          values: [
            [
              new Date().toISOString(),
              "ERROR",
              "AGENT_EXECUTION",
              error.message,
              "failed",
            ],
          ],
        },
      });
    } catch (logError) {
      console.error("[AGENT] Could not log error to sheet:", logError);
    }

    return {
      status: 500,
      message: "Agent execution failed",
      error: error.message,
    };
  }
}

/**
 * Vercel serverless function handler
 */
export default async function handler(req, res) {
  console.log(`[${new Date().toISOString()}] API Request:`, req.method);

  // Only allow POST requests
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  // Run the agent
  const result = await runAgent();

  return res.status(result.status).json(result);
}
